services:
    redis:
        network_mode: host
        image: grokzen/redis-cluster
        container_name: redis
        restart: on-failure
        ports:
            - 30001-30006:30001-30006
        environment:
            - INITIAL_PORT=30001
            - REDIS_CLUSTER_IP=0.0.0.0
            - IP=0.0.0.0
        healthcheck:
            test: ["CMD", "redis-cli", "-p", "30001", "ping"]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 5s
    dotcom:
        network_mode: host
        depends_on:
            - redis
        build:
            context: ../
            dockerfile: ./deploy/dotcom/dev/1/Dockerfile
        environment:
            - MIX_ENV=dev
            - CMS_API_BASE_URL=https://live-mbta.pantheonsite.io
            - OPEN_TRIP_PLANNER_URL=http://otp2-local.mbtace.com
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - MBTA_API_BASE_URL=${MBTA_API_BASE_URL}
            - MBTA_API_KEY=${MBTA_API_KEY}
            - PORT=4001
            - WEBPACK_PORT=8092
            - WARM_CACHES=false
            - REDIS_PORT=30001
        expose:
            - 4001
        healthcheck:
            test: curl --fail http://localhost:4001/_health || exit 1
            interval: 15s
            retries: 5
            start_period: 100s
            timeout: 30s
        volumes:
            - ../:/app
