name: Run end-to-end tests on deployment

on:
  - deployment_status

jobs:
  cypress:
    # only runs this job on successful deploy to a staging server
    if: github.event.deployment_status.state == 'success' && contains('dev-green dev-blue', github.event.deployment_status.environment)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          working-directory: apps/site/assets
          config: baseUrl=${{ github.event.deployment_status.environment_url }}
          build: npx cypress info
          spec: |
            cypress/e2e/screenshots.cy.js
            cypress/e2e/homepage.cy.js
            cypress/e2e/global_navigation.cy.js
      - uses: ./.github/actions/build-app
      - uses: cypress-io/github-action@v6
        timeout-minutes: 15
        with:
          working-directory: apps/site/assets
          install: false # already installed
          config: baseUrl=http://localhost:4002
          start: npm run test-server
          build: npx cypress info
          wait-on: 'http://localhost:4002'
          spec: |
            cypress/e2e/support_form.cy.js
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
