name: Run end-to-end tests on deployment

on:
  - deployment_status

jobs:
  cypress:
    # only runs this job on successful deploy
    if: github.event.deployment_status.state == 'success'
    name: Cypress tests
    runs-on: ubuntu-latest
    # stop the job if it runs over 10 minutes
    # to prevent a hanging process from using all your CI minutes
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      # will NPM install everything, incl. Cypress & plugins
      - uses: cypress-io/github-action@v6
        with:
          working-directory: apps/site/assets
          config: baseUrl=${{ github.event.deployment_status.environment_url }}
          build: npx cypress info
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: apps/site/assets/cypress/screenshots
          if-no-files-found: ignore
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: apps/site/assets/cypress/videos
          if-no-files-found: ignore

  